# Generated by Django 4.1.4 on 2022-12-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('year', models.PositiveSmallIntegerField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
